### ISSUE TITLE
Feature update to Windows 10, version 20H2

### ISSUE THREAD

**Issue by chrispbaker83** [GoobyCorp/fspd#1]
Hello,

Code was working great until Feature update version 20H2 was installed on my machine.

Are you able to fix the issue?

Thanks

**Comment by chrispbaker83** [comment]
Traceback (most recent call last):
  File "E:\...\fspd.py", line 705, in <module>
    main()
  File "E:\...\fspd.py", line 697, in main
    with ThreadingUDPServer((args.address[0], args.address[1]), FSPRequestHandler) as server:
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10049] The requested address is not valid in its context

**Comment by chrispbaker83** [comment]
The IP of the machine running the FSP server had changed. Your program still works flawlessly. Thanks
